# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:               From the Software Development Trenches Blog
description:         'Thoughts on Software Development by <a href="https://twitter.com/cjlotz" target="_blank">@cjlotz</a>.'
url:                 http://hyde.getpoole.com
baseurl:             /

paginate:            5

# About/contact
author:
  name:              Carel Lotz
  url:               https://twitter.com/cjlotz

# Custom vars
tag_page:           '/tags/'

# Google services
google_analytics:    UA-94090631-1

gems: [jekyll-paginate, jekyll-gist]
