# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:           pretty

# Setup
title:               From the Software Development Trenches
description:         'Thoughts on Software Development by <a href="https://twitter.com/cjlotz" target="_blank">@cjlotz</a>.'
url:                 http://hyde.getpoole.com
baseurl:             /

paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Carel Lotz
  url:               https://twitter.com/cjlotz

# Custom vars
version:             2.0.0

#github:
#  repo:              https://github.com/poole/hyde

# Google services
google_analytics:    UA-94090631-1

gems: [jekyll-paginate, jekyll-gist]
